name: CI

on:
  push:
    branches: [master, homolog]
  pull_request:
    branches: [master, homolog]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build dll
        run: |
          make clean
          make api

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          make tests
          make run_tests
